.TH YDPDICT 1 "July 1, 2007"
.SH NAME
ydpdict \- an interface for Collins and Langenscheidt dictionaries
.SH SYNOPSIS
.B ydpdict [
.BI options
.B ]

.SH DESCRIPTION
.B ydpdict
is an ncurses interface for English-Polish and Polish-English Collins
dictionaries, as well as German-Polish and Polish-German Langenscheidt
dictionaries, which are distributed by Young Digital Planet.
.PP
.B ydpdict
tries to load the configuration file from the following locations (reads only
the first one found):
.TP
1)
.BI ~/ydpdict.conf
.TP
2)
.BI ~/.ydpdictrc
.TP
3)
.BI /etc/ydpdict.conf

.SH OPTIONS
.TP
.BI \-e\ [\-\-eng]
Starts the English-Polish dictionary (default).
.TP
.BI \-p\ [\-\-pol]
Starts the Polish-English dictionary.
.TP
.BI \-g\ [\-\-ger-pol]
Starts the German-Polish dictionary.
.TP
.BI \-o\ [\-\-pol-ger]
Starts the Polish-German dictionary.
.TP
.BI \-f\ [\-\-path=PATH]
Sets the path to data files.
.TP
.BI \-c\ [\-\-cdpath=PATH]
Sets the path to the CD. (For audio sample files).
.TP
.BI \-P\ [\-\-player=PATH]
Sets the path to the WAV file player.
.TP
.BI \-w\ [\-\-word=WORD]
Starts the dictionary and translates the specified word.
.TP
.BI \-A\ [\-\-audio=DEVICE]
Sets the default audio device.
.TP
.BI \-\-version
Displays the version of the program.
.TP
.BI \-h\ [\-\-help]
Shows command line options.
.SH AUTHOR
.B ydpdict
was written by Wojtek Kaniewski <wojtekka@toxygen.net>. Latest version can be
found at
.I http://toxygen.net/ydpdict/
