.TH YDPDICT 1 "13 kwietnia 2006"
.SH NAZWA
ydpdict \- interfejs słowników Collinsa
.SH SKŁADNIA
.B ydpdict [
.BI opcje
.B ]

.SH OPIS
.B ydpdict
jest korzystającym z biblioteki ncurses interfejsem służącym do obsługi
multimedialnych słowników: angielsko-polskiego, polsko-angielskiego, 
niemiecko-polskiego i polsko-niemieckiego Collinsa.
.PP
.B ydpdict
szuka pliku konfiguracyjnego w następujących miejscach (czytany jest tylko pierwszy znaleziony plik):
.TP
1)
.BI ~/ydpdict.conf
.TP
2)
.BI ~/.ydpdictrc
.TP
3)
.BI /etc/ydpdict.conf

.SH OPCJE
.TP
.BI \-e\ [\-\-eng]
Uruchamia słownik angielsko-polski (domyślne).
.TP
.BI \-p\ [\-\-pol]
Uruchamia słownik polsko-angielski.
.TP
.BI \-g\ [\-\-ger-pol]
Uruchamia słownik niemiecko-polski.
.TP
.BI \-o\ [\-\-pol-ger]
Uruchamia słownik polsko-niemiecki.
.TP
.BI \-f\ [\-\-path=ŚCIEŻKA]
Podaje ścieżkę do plików danych.
.TP
.BI \-c\ [\-\-cdpath=ŚCIEŻKA]
Podaje ścieżkę do płyty CD.
.TP
.BI \-P\ [\-\-player=ŚCIEŻKA]
Podaje ścieżkę do odtwarzacza plików WAV.
.TP
.BI \-w\ [\-\-word=SŁOWO]
Uruchamia słownik i tłumaczy podane słowo.
.TP
.BI \-\-version
Wyświetla wersję programu.
.TP
.BI \-h\ [\-\-help]
Wyświetla tekst pomocy.
.SH AUTOR
.B ydpdict
został napisany przez Wojtka Kaniewskiego <wojtekka@toxygen.net>. Najnowszą
wersję można znaleźć pod adresem
.I http://toxygen.net/ydpdict/
