.TH YDPDICT 1 "1 grudnia 2004" 
.SH NAZWA
ydpdict \- interfejs s³owników Collinsa
.SH SK£ADNIA
.B ydpdict [
.BI opcje
.B ]

.SH OPIS
.B ydpdict
jest korzystaj±cym z biblioteki ncurses interfejsem s³u¿±cym do obs³ugi
multimedialnych s³owników: angielsko-polskiego, polsko-angielskiego, 
niemiecko-polskiego i polsko-niemieckiego Collinsa.
.PP
.B ydpdict
szuka pliku konfiguracyjnego w nastêpuj±cych miejscach (czytany jest tylko pierwszy znaleziony plik):
.TP
1)
.BI ~/ydpdict.conf
.TP
2)
.BI ~/.ydpdictrc
.TP
3)
.BI /etc/ydpdict.conf

.SH OPCJE
.TP
.BI \-a\ [\-\-ang]
Uruchamia s³ownik angielsko-polski (domy¶lne).
.TP
.BI \-p\ [\-\-pol]
Uruchamia s³ownik polsko-angielski.
.TP
.BI \-o\ [\-\-niem-pol]
Uruchamia s³ownik niemiecko-polski.
.TP
.BI \-d\ [\-\-pol-niem]
Uruchamia s³ownik polsko-niemiecki.
.TP
.BI \-n\ [\-\-nopl]
Wy³±cza wy¶wietlanie polskich znaków diakrytycznych.
.TP
.BI \-i\ [\-\-iso]
Wy¶wietla polskie literki w standardzie ISO-8859-2.
.TP
.BI \-u\ [\-\-unicode]
Wy¶wietla polskie literki u¿ywaj±c unikodu.
.TP
.BI \-U\ [\-\-unicodeset]
Prze³±cza konsolê w tryb unikodu na czas dzia³ania.
.TP
.BI \-f\ [\-\-path=¦CIE¯KA]
Podaje ¶cie¿kê do plików danych.
.TP
.BI \-c\ [\-\-cdpath=¦CIE¯KA]
Podaje ¶cie¿kê do p³yty CD.
.TP
.BI \-P\ [\-\-player=¦CIE¯KA]
Podaje ¶cie¿kê do odtwarzacza plików WAV.
.TP
.BI \-w\ [\-\-word=S£OWO]
Uruchamia s³ownik i t³umaczy podane s³owo.
.TP
.BI \-\-version
Wy¶wietla wersjê programu.
.TP
.BI \-h\ [\-\-help]
Wy¶wietla tekst pomocy.
.SH AUTOR
.B ydpdict
zosta³ napisany przez Wojtka Kaniewskiego <wojtekka@irc.pl>. Najnowsz±
wersjê mo¿na znale¼æ pod adresem
.I http://toxygen.net/ydpdict/
